# Generated by Django 3.2.13 on 2022-09-26 20:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CMPAChecklist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('location', models.CharField(max_length=30)),
                ('supportNeeded', models.CharField(max_length=30)),
                ('bandPMA', models.IntegerField(max_length=1)),
                ('bandPMO', models.IntegerField(max_length=1)),
            ],
        ),
    ]
