# Generated by Django 3.2.13 on 2022-09-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpachecklist',
            old_name='supportNeeded',
            new_name='support',
        ),
        migrations.AlterField(
            model_name='cmpachecklist',
            name='bandPMA',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cmpachecklist',
            name='bandPMO',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
