# Generated by Django 3.2.13 on 2022-09-30 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20220930_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmpachecklist',
            old_name='bandPMA',
            new_name='band_pma',
        ),
        migrations.RenameField(
            model_name='cmpachecklist',
            old_name='bandPMO',
            new_name='band_pmo',
        ),
    ]
