# Generated by Django 3.2.13 on 2022-10-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220930_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cmpachecklist',
            name='band_pma',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='cmpachecklist',
            name='band_pmo',
            field=models.CharField(max_length=2),
        ),
    ]
