# Generated by Django 4.1.2 on 2022-10-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_cmpachecklist_band_pma_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cmpachecklist",
            name="band_pma",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="band_pmo",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="contract_length",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="contract_tcv",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="contract_type",
            field=models.CharField(blank=True, default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="customer_name",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="deferral",
            field=models.CharField(blank=True, default="", max_length=44),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="ippf",
            field=models.CharField(blank=True, default="", max_length=44),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="location",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="project_code",
            field=models.CharField(blank=True, default="", max_length=60),
        ),
        migrations.AlterField(
            model_name="cmpachecklist",
            name="support",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
