# Generated by Django 4.1.2 on 2022-10-19 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_alter_cmpachecklist_band_pma_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cmpachecklist",
            name="user_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
    ]
